slam_toolbox:
  ros__parameters:
    # Don’t use simulated time on a real robot
    use_sim_time: false  

    # Optimization plugins
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None

    # Frame and topic names
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /scan

    # Mode and map saving
    mode: mapping          # switch to "localization" once your map is built
    use_map_saver: true

    # SLAM update rates
    throttle_scans: 1
    map_update_interval: 1.0   #was 5.0
    transform_publish_period: 0.02
    update_rate: 20.0

    # Map parameters
    resolution: 0.05
    min_laser_range: 0.0
    max_laser_range: 20.0

    # Timing and buffer
    minimum_time_interval: 0.5
    transform_timeout: 0.2
    tf_buffer_duration: 30.0

    # Performance tuning
    stack_size_to_use: 40000000
    enable_interactive_mode: true
    debug_logging: false

    # Scan matching / general parameters
    use_scan_matching: true
    use_scan_barycenter: true
    minimum_travel_distance: 0.5
    minimum_travel_heading: 0.5
    scan_buffer_size: 10
    scan_buffer_maximum_scan_distance: 10.0

    # Loop closure parameters
    do_loop_closing: true
    loop_search_maximum_distance: 3.0
    loop_match_minimum_chain_size: 10
    loop_match_maximum_variance_coarse: 3.0
    loop_match_minimum_response_coarse: 0.35
    loop_match_minimum_response_fine: 0.45

    # Correlation search parameters
    correlation_search_space_dimension: 0.5
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.1

    # Loop closure search params
    loop_search_space_dimension: 8.0
    loop_search_space_resolution: 0.05
    loop_search_space_smear_deviation: 0.03

    # Scan matcher parameters
    distance_variance_penalty: 0.5
    angle_variance_penalty: 1.0
    fine_search_angle_offset: 0.00349
    coarse_search_angle_offset: 0.349
    coarse_angle_resolution: 0.0349
    minimum_angle_penalty: 0.9
    minimum_distance_penalty: 0.5
    use_response_expansion: true
    min_pass_through: 2
    occupancy_threshold: 0.1
